### book index
GET http://localhost:3000/books.json

### book show
GET http://localhost:3000/books/5.json

### book create
POST http://localhost:3000/books.json
Content-Type: application/json

{
  "input_id": "103",
  "input_name": "Skin in the game",
  "input_author": "nassim taleb",
  "input_price": "30",
  "input_isbn": "3287927-1"
}

### book update
PATCH http://localhost:3000/books/6.json
Content-Type: application/json

{
  "name": "Economic",
  "author": "Bernard",
  "price": "50",
  "isbn": "328913-2"
}

### book destroy
DELETE http://localhost:3000/books/4.json